default_fields = ["title", "overview"]

[fields.title.Text]
indexed = true
stored = true
term_vectors = true

[fields.overview.Text]
indexed = true
stored = true
term_vectors = true

[fields.genres.Text]
indexed = true
stored = true
term_vectors = false

[fields.poster.Text]
indexed = false
stored = true
term_vectors = false

[fields.release_date.Integer]
indexed = true
stored = true

[embedders.clip_embedder]
type = "candle_clip"
model = "openai/clip-vit-base-patch32"

[fields.poster_vec.Hnsw]
dimension = 512
distance = "Cosine"
embedder = "clip_embedder"
